name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: sample 1
      id: sample-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: sample 1
        setup-command: ''
        command: python sum_of_two_numbers.py
        input: |-
          1
          2
        expected-output: '3'
        comparison-method: exact
        timeout: 10
        max-score: 8
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SAMPLE-1_RESULTS: "${{steps.sample-1.outputs.result}}"
      with:
        runners: sample-1
